"""add asset_metrics table

Revision ID: 1e9ee95e0ce8
Revises: e744cf9079f7
Create Date: 2026-02-17 08:47:10.235796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9ee95e0ce8'
down_revision: Union[str, Sequence[str], None] = 'e744cf9079f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('daily_return', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cumulative_return_30d', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volatility_30d', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_metrics_asset_date', 'asset_metrics', ['asset_id', 'date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_asset_metrics_asset_date', table_name='asset_metrics')
    op.drop_table('asset_metrics')
    # ### end Alembic commands ###
